### ISSUE TITLE
Python GUI Development

### ISSUE THREAD

**Issue by ghost** [umayanga123/scpp_python_node#1]
How about any plugin or framework for python based GUI developments ? Any references please?

**Comment by ghost** [comment]
Sorry I haven't used any, but while reading I came across **Tkinter** as a solution several times. Hope this might be helpful @umayanga123.
_References:-_ 
- [http://insights.dice.com/2014/11/26/5-top-python-guis-for-2015/](url)(see the comments section as well)
- Tkinter: [http://www.tutorialspoint.com/python/python_gui_programming.htm](url)

**Comment by umayanga123** [comment]
cannot assess above link.

**Comment by ghost** [comment]
please copy and paste the URLS in the URL bar and navigate @umayanga123 .

**Comment by umayanga123** [comment]
yes ,all ready we use , Tkinter and i think , we are not going to very complexUI  ,so we can manage this hard coding GUI.
