### ISSUE TITLE
GET query seems to be bit useless

### ISSUE THREAD

**Issue by ghost** [umayanga123/scpp_python_node#2]
GET query which is currently there, seems to be bit increase the workload unnecessarily. It's better to apply some refactoring regarding it.  @umayanga123 @Dulakshi

**Comment by umayanga123** [comment]
#GET and #PUT also , same. I think it protocol calling scenario not applicable to our system. but ,using get method we can request any public key , of specific user.so ,i think , keep this method ,not get early #refactoring decisioned.
